In [1]:
import os
import numpy as np
import pandas as pd
import random

from ipynb.fs.full.Finance_data_preparation import data_generator
from sklearn.model_selection import train_test_split

# Creating First Big Data

In [2]:
def calculate_features(Path = 'C:\\Users\\ali\\finance_Data\\Data',t=1):
    namad = os.listdir(Path)
    Origin_Key = ['TICKER','date','open','high','low','close','volume','value','num','YES-PRICE','code','EN-NAME','NAME','SHAMSI','akharin']
    key = ['code', 'date', 'open', 'high', 'low', 'close', 'volume', 'value', 'num', 'akharin']
    total = pd.DataFrame()
    for i in namad:
        data = pd.read_excel(Path+'\\'+i)
        data.columns = Origin_Key
        data = data[key]
        
        data = data_generator(data,t)
        total = pd.concat([total, data], ignore_index=True)

    data = total.dropna(axis=0)
    
    name = 'all_'+str(t)+'.csv'
    data.to_csv(name, index=False)
    print ('Done!')

In [3]:
calculate_features()
data = pd.read_csv('all_1.csv')

ipynb.fs.full.Finance_data_preparation:441: RuntimeWarning: invalid value encountered in log
ipynb.fs.full.Finance_data_preparation:441: RuntimeWarning: invalid value encountered in double_scalars

Done!

In [4]:
data

,code,date,open,high,low,close,volume,value,num,akharin,...,Accumulative_Swing_Index,Chopiness_Index50,KVO34_55,KVO34_55_34,Upper_Super_Trend10,Lower_Super_Trend10,AMA50_5,Ehler_Fisher_Transformation15_3,WWSA50,Y
0,ALIR,20080106,246.73,252.0,247.0,251.74,304,3.084316e+06,2,251.74,...,-31091,1.800189,-16335.366457,-20322.333295,7.730463e+02,-2.740463e+02,251.74,-0.146664,313.335716,0.000000
1,ALIR,20080108,246.73,252.0,247.0,251.62,2964,3.005401e+07,3,251.62,...,-31056,1.798800,-15161.945623,-20027.453999,6.988203e+02,-1.998203e+02,251.74,-0.155129,313.333316,-0.047668
2,ALIR,20080109,246.61,251.0,247.0,251.40,5519,5.593152e+07,3,251.40,...,-31014,1.797402,-14118.897812,-19689.822217,5.739122e+02,-7.591221e+01,251.62,-0.163773,313.328916,-0.087433
3,ALIR,20080112,246.39,246.0,246.0,246.39,883,8.940375e+06,3,246.39,...,-31495,1.775358,-13042.418838,-19309.970596,5.728785e+02,-8.087847e+01,251.40,-0.171348,313.228716,-1.992840
4,ALIR,20080113,241.48,251.0,241.0,244.03,349475,3.504850e+09,98,244.03,...,-31500,1.677583,-19506.913120,-19321.224454,7.730688e+02,-2.810688e+02,246.39,-0.176823,313.181516,-0.957831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134114,YASA,20200923,23580.00,23580.0,23580.0,24790.00,41299,9.738304e+08,30,23580.00,...,10905830,0.025302,-36594.280536,-75351.701761,4.228480e+06,-4.181320e+06,24820.00,-0.112875,723.472160,-0.120870
134115,YASA,20200926,23560.00,23560.0,23560.0,24730.00,99161,2.336233e+09,73,23560.00,...,10905830,0.025264,-37776.857270,-73204.567790,4.557598e+06,-4.510478e+06,24790.00,-0.113994,722.272160,-0.242033
134116,YASA,20200927,23500.00,23500.0,23500.0,24730.00,2898,6.810300e+07,6,23500.00,...,10905830,0.025136,-36712.162531,-71119.287489,4.563141e+06,-4.516141e+06,24730.00,-0.142439,722.272160,0.000000
134117,YASA,20200928,23500.00,23500.0,23500.0,24730.00,1477,3.470950e+07,4,23500.00,...,10905830,0.025142,-35638.786676,-69091.830300,4.286780e+06,-4.239780e+06,24730.00,-0.182935,722.272160,0.000000
134118,YASA,20200929,23500.00,23500.0,23500.0,24720.00,9745,2.290075e+08,12,23500.00,...,10905830,0.025147,-34767.330083,-67130.430288,3.824377e+06,-3.777377e+06,24730.00,-0.229764,722.072160,-0.040437

# creating Info sheet (namad list and start & end date)

In [ ]:
def create_namad_list(data,Path = 'C:\\Users\\ali\\finance_Data\\Data',t)
    namad = os.listdir(Path)
    name = []
    path = []
    start = []
    end = []
    exist = []
    for i in namad:
        exist = np.sign(data.COD.str.contains(i.split('.')[0]).sum())
        if exist == 0:
            name.append(i.split('.')[0])
            path.append(Path + '\\' + i)
            start.append(0)
            end.append(0)

    X = {'name':name , 'path':path  , 'start':start , 'end':end }
    Info = pd.DataFrame(X)
    
    name = 'Info_'+str(t)+'.csv'
    Info.to_csv(name, index=False)
    print('Done!')

# function for back testing

In [ ]:
"""
namad_for_test = random,selected,full
default = full 
nft_value = ...
if namad_for_test = random
    nft_value = nomber of namad for test that should be selected randomly
if namad_for_test = selected
    nft_value = list of selected namad for test
    
date_of_test = full,random,selected,from_to
defualt = full
dft_value = ...
if date_for_test = random
    dft_value = fraction of date that should be selected randomly
if date_for_test = selected
    dft_value = list of selected days
if date_for_test = from_to
    dft_value = 1- start 2- end    

    
"""
def back_testing(model , data , Path = 'C:\\Users\\ali\\finance_Data\\Data' ,
                 namad_for_test = 'full', nft_value = [] ,
                 date_of_test = 'random' , dft_value = [] 
                )
    if namad_for_test == 'full':
        if date_of_test == 'full':
            test_data = data
        elif date_of_test == 'random':
            random_sample = random.sample(range(len(data)), size=(dft_value))
            test_data = data_X.loc[random_sample,]
        elif date_of_test == 'selected':
            test_data = data.loc[(data.DTYYYYMMDD .isin(dft_value))]
        elif date_of_test == 'from_to':
            test_data = data.loc[(data.DTYYYYMMDD >= dft_value(0)) & (data.DTYYYYMMDD<= dft_value(1))]
        else:
            print('wrong argomant for "date_for_test"')
    elif namad_for_test == 'random':
        random_sample = random.sample(data.code.unique().tolist(), size=(nft_value))
        data = data.loc[data.code.isin(random_sample)]
        if date_of_test == 'full':
            test_data = data
        elif date_of_test == 'random':
            random_sample = random.sample(range(len(data)), size=(dft_value))
            test_data = data_X.loc[random_sample,]
        elif date_of_test == 'selected':
            test_data = data.loc[(data.DTYYYYMMDD .isin(dft_value))]
        elif date_of_test == 'from_to':
            test_data = data.loc[(data.DTYYYYMMDD >= dft_value(0)) & (data.DTYYYYMMDD<= dft_value(1))]
        else:
            print('wrong argomant for "date_for_test"')
    elif namad_for_test == 'selected':
        data = data.loc[data.code.isin(nft_value)]
        if date_of_test == 'full':
            test_data = data
        elif date_of_test == 'random':
            random_sample = random.sample(range(len(data)), size=(dft_value))
            test_data = data_X.loc[random_sample,]
        elif date_of_test == 'selected':
            test_data = data.loc[(data.DTYYYYMMDD .isin(dft_value))]
        elif date_of_test == 'from_to':
            test_data = data.loc[(data.DTYYYYMMDD >= dft_value(0)) & (data.DTYYYYMMDD<= dft_value(1))]
        else:
            print('wrong argomant for "date_for_test"')
    else:
        print('wrong argomant for "namad_for_test"')
    
    y_test = data.Y
    X_test = data.drop(columns = ['Y','code','date'])
    
    return X_test,y_test

In [ ]:
X = data_X
            X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=42)